
#mybatis日志打印
logging:
  level:
    com.boss.demo.mapper: debug
spring:
  #多环境配置
  profiles:
    active: dev
  datasource:
    druid:
      # 开启druid监控 http://localhost:8081/druid/index.html
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      #监控路径
      aop-patterns: com.boss.demo.controller.*
      web-stat-filter:
        enabled: true
          url-pattern: /api/*
          session-stat-enable: true
        #排除一些不必要的拦截
        exclusions: .js,.gif,.jpg,.bmp,.png,.css,.ico,/druid/*
  #mybatis配置
#mybatis:
#  type-aliases-package: com.boss.demo.entity
#  mapper-locations: classpath:mapper/masterDataSource/*.xml
  #多数据源配置
#  datasource:
#    run: #数据源1
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 123456
#    debug: #数据源2
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/demo2?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 123456
