#mysql配置
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver

#mybatis配置
#mybatis:
#  type-aliases-package: com.boss.demo.entity
#  mapper-locations: classpath:mapper/masterDataSource/*.xml
  #自动识别使用的数据库类型相关
#  configuration:
#    database-id: ${database.type}
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis日志打印
logging:
  level:
    com.boss.demo.mapper: debug
#端口配置
server:
  port: 8081


#多数据源配置
spring:
  datasource:
    master: #数据源1
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    slaver: #数据源2
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

#database:
#  type: oracle
